### PR TITLE
Makes sure that the last captured input is used to run validations instead of the first input

### PR DESCRIPTION
**Pull request by skress**
This change fixes the bug that is described as 'problem 1' in https://github.com/thomashoneyman/purescript-halogen-formless/issues/48#issuecomment-577846309.

### CODE REVIEW

**Comment by skress** [comment]
I've updated the PR, it should now also fix the second problem.

**Comment by thomashoneyman** [comment]
@skress Thank you so much for your work on this -- as you can tell, it's not a trivial problem and I haven't been sure how to fix it so far. I won't be able to fully review your work until tomorrow, over the weekend, but just wanted to thank you for putting in the effort and let you know that it's on my radar.

**Review by thomashoneyman — APPROVED** [review]
Great work tracking this down.

I can see how this addresses the case where no input is entered, validation and `atomic` complete, and the last value caught by atomic gets written instead of the actual last value. And it also addresses the case where an old state is updated instead of the most current state when validation finishes. Thanks for the clear code!

@naglalakk I am going to go ahead and merge this as I believe it addresses your issue. However, if you have a chance to test this out yourself I'd appreciate hearing from you about whether your issue is resolved.

Thanks again to both of you for opening and solving the issue!

**Comment by naglalakk** [comment]
Hi @thomashoneyman, @skress. I just verified this and this PR is working 100% for me. Thank you so much for following up on this and @skress for tackling this. Great work! <3

**Pull request merged**
