### PR TITLE
Expose Halogen's `input` type

### PR DESCRIPTION
**Pull request by JordanMartinez**
## What does this pull request do?

The same thing as citizennet/purescript-halogen-select#45: expose the Halogen `input` type. In addition, it changes Formless' `Message` type and `handleMessage` functions to `Event` and `handleEvent`, respectively, as these better represent their function: an event that Formless produces and the end-user can choose to handle/ignore.

Besides the opening comment, Thomas provided a [nice summary in his own words](https://github.com/citizennet/purescript-halogen-select/pull/45#issuecomment-494194389) of what that PR does.

## Where should the reviewer start?

- Formless/Types/Component.purs
- Formless/Component.purs

## How should this be manually tested?

No need to test anything since we're just exposing what's hidden in Halogen.

## Other Notes:

- I removed extra whitespace in the initial commit to prevent noise later on
- I also changed the Halogen 4 `ps` type name to the Halogen 5 `slots` type name in `Formless/Types/Component.purs` (or maybe it was the other Component.purs file?)
- `F.Component` had an extra type parameter `st` that wasn't ever used. I was forced to remove that to get the code to compile.

> Does the project documentation need to be updated? 

We should update the docs for `Input form st m` to clarify that it is no longer the component's input value.

> Should we introduce a new example, or update any existing examples? 

Due to not exposing the `input` type, many of the examples were sort of "shoved" into another Halogen component's `render` function. These can now be properly separated into their own stand-alone files

> Does this PR require any other follow-up tasks?

Currently waiting for a response to be made [in this comment thread in the linked PR above](https://github.com/citizennet/purescript-halogen-select/pull/45#discussion_r285846362) as it will set a precedent for how we rename a few things due to exposing the input type.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Thanks @JordanMartinez! I have a few thoughts on this one.

> F.Component had an extra type parameter st that wasn't ever used. I was forced to remove that to get the code to compile.

That's due to replacing the `Input form st m` type with the `input` type parameter.

> We should update the docs for `Input form st m` to clarify that it is no longer the component's input value.

Or rather that it _is_ the Formless component's input value, just as `Message` is the Formless component's output value, but that extended components will probably not see them because they have been replaced with the custom `input` and `msg` type parameters. When you are writing your form component you still have to give Formless the input type it needs and handle the message type it outputs, but the user of _your_ component will not.

This is still confusing. The input and output types are now strange; I still have them in my mind as `Input` is the form input and `Message` is the form output, it's just the user gets to provide a new mapping from `input -> Input` and `Message -> HalogenM ... msg ...` to modify the inputs and outputs of the component. (That, in turn, reminds me of profunctors...but this doesn't quite fit.)

I've stuck with `Input` being my idea of the base component's input value because if you don't change anything (do any extension) then it really _is_ the component's input value. But I haven't got a good way of explaining or documenting this yet.

I'm working on a replacement to the `-renderless` library which will simply be documentation on renderless as a pattern (not a library) and this is one of the last remaining bits to tweak about it.

> Due to not exposing the input type, many of the examples were sort of "shoved" into another Halogen component's render function. These can now be properly separated into their own stand-alone files

I would prefer to do that -- for each example, perhaps a `Page.purs` and `Form.purs`? We can get rid of the Spec name altogether and consider it largely an internal detail, the way that Halogen almost never talks about `ComponentSpec`. Is that something you're open to doing in this PR?

**Comment by JordanMartinez** [comment]
> I would prefer to do that -- for each example, perhaps a Page.purs and Form.purs? We can get rid of the Spec name altogether and consider it largely an internal detail, the way that Halogen almost never talks about ComponentSpec. Is that something you're open to doing in this PR?

Yeah! That's partly why I brought it up.

> I'm working on a replacement to the -renderless library which will simply be documentation on renderless as a pattern (not a library) and this is one of the last remaining bits to tweak about it.

Let me know when it's ready so I can link to it from the `learn-halogen` repo.

<hr>

Ok, now to respond to your comment with a really long answer (sorry!)

> I've stuck with `Input` being my idea of the base component's input value because if you don't change anything (do any extension) then it really is the component's input value. But I haven't got a good way of explaining or documenting this yet.

Oo....... That's... a really good point. Actually, wait...

> if you don't change anything (do any extension) then it really is the component's input value. 

Is that actually true? To explain myself, I'm going to review a few things for context.

This is my understanding of the purpose of the `input` type for Halogen components: 
1. one can use it (or not) to create the component's initial state (i.e. Halogen's `initialState` function)
2. one can use it (or not) to update the child component when the parent re-renders (i.e. Halogen's `receive` function)

When I write a complex Halogen component, I can use this to pass values from the parent into the child component. However, when I write a simple Halogen component that doesn't need an `input` value when creating its initial state and which never responds to a parent component's re-rendering, I still have to pass in a value as the child's input. So, I use `Unit` and then ignore that `unit` value via `const initialState`. In such a context, despite `unit` being the component's `input` value that is then ignored, I don't call `initialState` the component's "real" input value. Rather, I refer to it for what it is: the component's initial state. 
Let's compare our Formless `Input` type situation (where the Halogen `input` value we pass into `mkInput` does not affect the value that `mkInput` returns) to the Halogen component example I described above. Since my Halogen example's `initialState` function ignores the Halogen `input` value and functions as creating the initial state of the component, why would the Formless `Input` type, when the end-user similarly uses `unit` as the `input` value and then ignores it using `const`, be considered the component's "real" input value?

By exposing the Halogen `input` type (which also covers the `receive` function), the Formless `Input` type now only exists for one reason: to allow the end-user to set the Formless component's initial state in three ways:
- sets the `validators` label that's otherwise hidden from public modification in the Formless's `internalState` label
- sets the values of the labels they added to the component's state's record type
- sets whether their input fields (e.g. textfield, dropdown, etc.) have an initial value or not

I'll state this differently. The full Formless component's state type (after looking at the source code) appears to be this:
```purescript
type State form st m =
  { validity :: ValidStatus
  , dirty :: Boolean
  , submitting :: Boolean
  , errors :: Int
  , submitAttempts :: Int
  , form :: form Record FormField
  , internalState :: InternalState form m            
  {- additional labels added by end-user
  , addedLabel :: String                                 -}
  }
```
I'll ask a rhetorical question: "Why not get rid of the Formless `Input` type in the first place and just expose the full Formless `State` type?" I believe there are four parts to this answer.
1. because the end-user shouldn't be able to set or change some of those Formless-specific values like the `internalState` label. Doing so would create bugs.
2. because, when creating the initial state of the Formless component, some values are going to be the same no matter what the end-user does. Whether or not they extend the component's state with new labels, the `submitAttempts` will always be 0. There's no need to allow the end-user to set this value when defining the initial state of the Formless component as its boilerplate code that Formless can take care of (i.e. every time `Build.insert` is used). 
3. because, when creating the initial state of the Formless component, 2-3 values always need to be specified by the end-user. First, the initial values of their input fields (i.e. textfield, dropdown, etc.) of the form. Second, the way to validate whether each of their input fields have valid content. Third, the initial values of any labels they added to the state record type.
4. because it's better to hide "type noise" (i.e. unneeded/unused things in a type that distract a developer from their purpose) by using a type that is simpler than the full Formless `State` type. For right now, that simpler type is the Formless `Input` type.

Again, AFAICT, the Formless (and Select) `Input` type now functions as a (sorry for the long type name) `InitialUnfinishedStateThatHidesAFewLabelsToPreventBugsAndBoilerplateForYourCovenience`

**Comment by JordanMartinez** [comment]
> Message is the form output

To me, `Message` is more like a Formless "event" of sorts than it is a Halogen message, but it seems that the code (as it currently stands) tries to pretend that Formless' `Message` is the same as a Halogen `Message`.

For example, I could write this
```purescript
formComponent :: F.Component ContactForm (Const Void) () Unit Contact Aff
formComponent = F.component (const formInput) $ F.defaultSpec 
  { render = renderFormless, handleMessage = const $ pure unit }
```
It would satisfy the type signature of `handleMessage`, but the underlying Halogen component isn't actually outputting a value of its `Message` type: `Contact`.

Rather, Formless `Message` acts more like an event: you can choose to handle it, ignore it, etc. The fact that a Formless-augmented Halogen component can produce a `Submitted formContent` event doesn't mean it's an actual message. Rather, we can choose to notify the parent that it has occurred (how we handle it here makes it seem like it's a Halogen `Message` type) or run some capability-based code using that value (i.e. `case _ of Submitted info -> saveFormInfo info; _ -> pure unit`, which doesn't produce a Halogen `Message` value at all).

**Comment by thomashoneyman** [comment]
I think I'm happy with `Event` + `handleEvent` + `mkInput` and things as they stand now. What do you think? Are you happy with this PR as it is?

**Comment by JordanMartinez** [comment]
Yup!

**Pull request merged**
